travis:
  secure:
    BINSTAR_TOKEN: fTf3nZKmeTEtFP0bhsrQ3FFgPToNhsVYCmmXw7tVUCrofIhlsmsDa6nE9fEdeLBzNtliEaIp3Yii10PXBejDYUSqU98o9Hr6vwICkoEP/rpK+S1bqppBHChd83u/3udnpFefBWv/5Xg7IUAvVahlZC8ZAWwf9Dzz3caHxEWzOH9jTJo8L6/UZ3NPOqXsRE3bTDrZVDLJDV3uaTMRGzDx4wT9z2ItdWAqJ/FKBcIiKfbBs4fqfi1p4MLWDcqBV8pLTh7LF5NuKhfxV6uY8WIG0r03UPbpP2SEj4Utl2PvWTzolTxmaarodJjkaut7kBcPqDzi7rJn9hLMNDnk6ao9at2tDnMXggzgiwYynLavjAnJbwlhTEEHF3F4UGkDHLXD0O7duShyqVNtvkjfQbg0vj597erUzlD+OVHGoEFUhcstNambxpC1oAHJAF60VK4DIsL1LCsFd4kuDyQ9B7HHZDvk/V8F2Qkl4ZVqkZINSLoWPDN+hMCkWHIZ2jTEXOTeA0PATTdxMFjlYVepEYbwCd2XKsKaTHlwgbXxl/Q/628TjKEPixjiteeQ5e4lawagEUSiec8yEsYdJbU7pRjDrmx6FCj6yFA2h2lykNlNj6TEg9rd+jXsici6atKDTLS30jTut7DTgi8E1ZM0IwYacWDdbk4swMD8HbZWaE6vO94=
conda_forge_output_validation: true
bot:
  automerge: true
